import * as docx from "docx";
import PptxGenJS from "pptxgenjs";
import PDFDocument from "pdfkit";
import * as xlsx from "xlsx";

/**
 * Service to generate documents in Base64 based on user requests via Chat.
 */
export class DocumentGeneratorService {
  /**
   * Generates a Base64 encoded string of the requested document type.
   *
   * @param format - "pdf", "docx", "xlsx", "pptx", "csv", "md"
   * @param title - The title of the document
   * @param raw_content - The raw text/markdown content generated by the AI
   */
  static async generate(
    format: "pdf" | "docx" | "xlsx" | "pptx" | "csv" | "md",
    title: string,
    raw_content: string
  ): Promise<string> {
    switch (format) {
      case "pdf":
        return this.generatePDF(title, raw_content);
      case "docx":
        return this.generateDOCX(title, raw_content);
      case "pptx":
        return this.generatePPTX(title, raw_content);
      case "xlsx":
        return this.generateXLSX(title, raw_content);
      case "csv":
        return this.generateCSV(title, raw_content);
      case "md":
      default:
        return this.generateMD(title, raw_content);
    }
  }

  private static stripMarkdown(text: string): string {
    return text
      .replace(/(\*\*|__)(.*?)\1/g, "$2") // bold
      .replace(/(\*|_)(.*?)\1/g, "$2") // italic
      .replace(/\[([^\]]+)\]\([^\)]+\)/g, "$1") // link
      .replace(/^#{1,6}\s*(.*)$/gm, "$1") // headers
      .replace(/`/g, "") // inline code
      .replace(/~~(.*?)~~/g, "$1"); // strikethrough
  }

  private static async generatePDF(title: string, content: string): Promise<string> {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ margin: 50 });
        const buffers: Buffer[] = [];

        doc.on("data", (buffer) => buffers.push(buffer));
        doc.on("end", () => {
          const pdfData = Buffer.concat(buffers);
          resolve(pdfData.toString("base64"));
        });

        // Branding / Title
        doc.fontSize(20).font("Helvetica-Bold").text(title, { align: "center" });
        doc.moveDown(1);

        // Content (stripping basic markdown for clean pdf output)
        const cleanContent = this.stripMarkdown(content);

        doc.fontSize(12).font("Helvetica").text(cleanContent, {
          align: "justify",
          lineGap: 5,
        });

        doc.end();
      } catch (err) {
        reject(err);
      }
    });
  }

  private static async generateDOCX(title: string, content: string): Promise<string> {
    // Basic Markdown translation to paragraphs
    const lines = content.split("\n");
    const paragraphs = lines.map((line) => {
      // Very basic heading detection
      if (line.startsWith("# ")) {
        return new docx.Paragraph({
          text: line.replace("# ", ""),
          heading: docx.HeadingLevel.HEADING_1,
        });
      } else if (line.startsWith("## ")) {
        return new docx.Paragraph({
          text: line.replace("## ", ""),
          heading: docx.HeadingLevel.HEADING_2,
        });
      } else if (line.startsWith("### ")) {
        return new docx.Paragraph({
          text: line.replace("### ", ""),
          heading: docx.HeadingLevel.HEADING_3,
        });
      }
      return new docx.Paragraph({
        children: [new docx.TextRun(this.stripMarkdown(line))],
      });
    });

    const doc = new docx.Document({
      sections: [
        {
          properties: {},
          children: [
            new docx.Paragraph({
              text: title,
              heading: docx.HeadingLevel.TITLE,
              alignment: docx.AlignmentType.CENTER,
            }),
            ...paragraphs,
          ],
        },
      ],
    });

    const b64 = await docx.Packer.toBase64String(doc);
    return b64;
  }

  private static async generatePPTX(title: string, content: string): Promise<string> {
    const pptx = new PptxGenJS();
    pptx.title = title;

    // Cover Page
    const coverSlide = pptx.addSlide();
    coverSlide.addText(title, {
      x: "10%",
      y: "40%",
      w: "80%",
      h: 1,
      fontSize: 32,
      bold: true,
      align: "center",
      color: "363636",
    });

    // Content Slides
    // Split by Markdown Headers if possible to create slides
    const slideContents = content.split(/(?=^#{1,2}\s)/gm);

    for (const section of slideContents) {
        if (!section.trim()) continue;
        const slide = pptx.addSlide();
        
        // Extract a "Slide Title" and "Slide Body"
        const lines = section.trim().split("\n");
        const slideTitle = this.stripMarkdown(lines[0] || "Details");
        const slideBody = this.stripMarkdown(lines.slice(1).join("\n").trim() || slideTitle);

        slide.addText(slideTitle, {
            x: "5%",
            y: "5%",
            w: "90%",
            h: 0.5,
            fontSize: 24,
            bold: true,
            color: "000000"
        });

        if (slideBody) {
             slide.addText(slideBody, {
                x: "5%",
                y: "15%",
                w: "90%",
                h: "80%",
                fontSize: 14,
                valign: "top",
                bullet: slideBody.includes("- ")
             });
        }
    }

    const b64 = await pptx.write({ outputType: "base64" });
    return b64 as string;
  }

  private static async generateXLSX(title: string, content: string): Promise<string> {
    // Attempt to extract tabular data or just put the raw content
    const wb = xlsx.utils.book_new();
    
    // Very naive CSV detection inside Markdown
    const csvBlocks = content.match(/```csv\n([\s\S]*?)```/);
    let ws;

    if (csvBlocks && csvBlocks[1]) {
       // Parse CSV block
       const rows = csvBlocks[1].trim().split('\n').map(row => row.split(',').map(cell => cell.trim()));
       ws = xlsx.utils.aoa_to_sheet(rows);
    } else {
       // Just put content into A1
       ws = xlsx.utils.aoa_to_sheet([[title], [], [this.stripMarkdown(content)]]);
    }

    xlsx.utils.book_append_sheet(wb, ws, "Export");
    const b64 = xlsx.write(wb, { type: "base64", bookType: "xlsx" });
    return b64;
  }

  private static async generateCSV(title: string, content: string): Promise<string> {
    const csvBlocks = content.match(/```csv\n([\s\S]*?)```/);
    let csvData = title + "\n\n" + this.stripMarkdown(content);
    if (csvBlocks && csvBlocks[1]) {
        csvData = csvBlocks[1];
    }
    return Buffer.from(csvData).toString("base64");
  }

  private static async generateMD(title: string, content: string): Promise<string> {
    const mdStr = `# ${title}\n\n${content}`;
    return Buffer.from(mdStr).toString("base64");
  }
}
